### ISSUE TITLE
How do I file an issue against SanntiS?

### ISSUE THREAD

**Issue by cymon** [Finn-Lab/emeraldBGC#4]
Hi @SantiagoSanchezF,

How do I file an issue against SanntiS? When I view the repo page (https://github.com/Finn-Lab/SanntiS) this is no "Issues" in the menu...

Thanks.

**Comment by mberacochea** [comment]
Hi @cymon 
I've just enabled the issues in https://github.com/Finn-Lab/SanntiS, please create any new "issues" with the tool there.
Thank you
