### ISSUE TITLE
emeraldBGC status / relationship to SanntiS?

### ISSUE THREAD

**Issue by dtdoering** [Finn-Lab/emeraldBGC#5]
Hello!

Just wanted to check my understanding of the status of emeraldBGC and its relation to the fork that is now SanntiS. It appears that emeraldBGC has now basically been deprecated and "renamed" to SanntiS for the ongoing/future development -- is this the case?

If that's not the case, could you clarify? Otherwise if that description is correct, perhaps you could indicate so in the README, GitHub description, etc as you see fit.

Thanks for any info!

**Comment by SantiagoSanchezF** [comment]
Hello!

Apologies for the late response , and thank you for reaching out with your question.

Yes, you are correct. The project formerly known as emeraldBGC has indeed been deprecated and has been rebranded as SanntiS for all ongoing and future developments. We appreciate your suggestion, and we will update the README and other GitHub repository details to reflect this change clearly.

Thank you again for your attention to this matter, and please let us know if you have any further questions.

Best regards,
Santiago
